### ISSUE TITLE
[WIP] Add HRC721/NFT tutorial

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/docs-home#14]
Page to update: https://github.com/harmony-one/docs-home/blob/master/developers/learn/tutorials/deploying-hrc721-nft.md

Reference to use: NFT tutorial reference to port from: https://forum.openzeppelin.com/t/create-an-nft-and-deploy-to-a-public-testnet-using-remix/6358

Replace the metadata part using ipfs as shown in https://docs.alchemy.com/alchemy/tutorials/how-to-create-an-nft/how-to-mint-a-nft#step-9-call-mint-nft-and-run-node-contract-interact-js

**Comment by johnwhitton** [comment]
Hi,
I've added this via gitbook.
Commit is https://github.com/harmony-one/docs-home/commit/6adcbc9422f9a3b847128abd79aab3f525ad3cf5
Page is https://docs.harmony.one/home/developers/learn/tutorials/deploying-hrc721-nft

@givp and @gupadhyaya 
Please review.
Specifically I deployed the NFT contract in [harmony testnet](https://explorer.pops.one/address/0xe9218ef3c209e1e7db8bef2e33f822006b44bcd7) and [minted an NFT token](https://explorer.pops.one/tx/0xd65c9bd74119ee7ce1734a69a1e1cda2cdd98beb80060906d21fe24331be7885)
I validated by adding the NFT Contract in Metamask but was unsure how to validate and see the NFT token minted.

**Comment by gupadhyaya** [comment]
thanks @johnwhitton
