### ISSUE TITLE
[WIP] Update band oracle guide

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/docs-home#15]
Where to update: https://github.com/harmony-one/docs-home/blob/master/developers/learn/tutorials/using-band-oracle.md

Reference working code: https://github.com/harmony-one/band_oracle

**Comment by Dewansahil** [comment]
@hypnagonia can take this

**Comment by gupadhyaya** [comment]
@hypnagonia also please update the instructions in https://github.com/harmony-one/docs-home/blob/master/developers/tools/oracle-band-protocol.md with code and examples from https://github.com/harmony-one/band_oracle repo. Also include the bridge contract address for testnet and mainnet
