### ISSUE TITLE
[Open] Add IPFS tutorial

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/docs-home#17]
Where to add? https://github.com/harmony-one/docs-home/blob/master/developers/learn/tutorials/using-ipfs.md

Content: search and find the common use cases of IPFS in ethereum and replicate.

Deliverables:
* Repo with IPFS integration example w/ README instructions
* Video tutorial

Reward
* 500 ONE w/o video
* 800 ONE w/ video

**Comment by spiritbro1** [comment]
hello if the ipfs using pinning service like infura or pinata is it okay?

**Comment by gupadhyaya** [comment]
> using pinning service like infura

yes piñata or infura is ok.

**Comment by givp** [comment]
@spiritbro1 https://explorer.harmony.one/tx/0x4aa2c04ae0de9e77f2130339841403a1e439672341c1ce0495729eb1860e0d17

**Comment by spiritbro1** [comment]
@givp thanks bro
