### ISSUE TITLE
[WIP] Update bridge sdk documentation

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/docs-home#21]
Where to update? https://github.com/harmony-one/docs-home/blob/master/developers/learn/tutorials/using-horizon-bridge-sdk.md

* Add the new sdk methods to https://docs.harmony.one/home/developers/tools/bridge/horizon/horizon-sdk with examples
* Add the tutorial [here](https://github.com/harmony-one/docs-home/blob/master/developers/learn/tutorials/using-horizon-bridge-sdk.md)

**Comment by potvik** [comment]
Done 
https://github.com/harmony-one/docs-home/blob/master/developers/learn/tutorials/using-horizon-bridge-sdk.md
