### ISSUE TITLE
[Open] Learn Solidity in 15 mins Tutorial

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/docs-home#22]
As part of our 1 million hackathon, we hope to attract many web2 developers and we need some basic web2 to web3 tutorials and examples. First and foremost would be learning solidity key concepts in 15 mins or so. 

Goal for this tutorial:
* Replicate https://learnxinyminutes.com/docs/solidity/ tutorial for harmony and also create a video walkthrough the tutorial.

Reward
* 800 ONE w/o video
* 3000 ONE w/ video

**Comment by sprect8** [comment]
Hi @givp I am interested in doing this task

**Comment by gupadhyaya** [comment]
@sprect8 can you take a jab at this first? sooner we get this, better. thank you. let me know if you have any questions.

**Comment by sprect8** [comment]
Hi @gupadhyaya I will do this one as a priority.

**Comment by sprect8** [comment]
Hi @gupadhyaya wanted to confirm your preference on the following:
- Are we using harmony one remix (https://ide.harmony.one/#optimize=false&evmVersion=null&version=soljson-v0.6.6+commit.6c089d02.js&gist=f490c0d51141dd0515244db40bbd0c17&runs=200)
- Will we use the Harmony One wallet? (harmony one remix support only harmony one wallet or the math wallet)

I'm building from a fork of the learning series (https://github.com/adambard/learnxinyminutes-docs) removing everything except the solidity series. I will be updating the screenshots.

Thanks! 
Victa

**Comment by gupadhyaya** [comment]
> of the learning seri

remix is good enough. I don't think we need harmony remix.

**Comment by sprect8** [comment]
Ok excellent thank you. i will complete this and submit for review

**Comment by sprect8** [comment]
Hi @gupadhyaya, I have updated the document in the repo https://github.com/sprect8/learn-solidity-in-15-minutes

I will be creating the youtube video based on the docs. It is a fork of the https://github.com/adambard/learnxinyminutes-docs with only the solidity tutorial in place.

**Comment by sprect8** [comment]
Hi @gupadhyaya, @givp, I've uploaded the video as well, please take a look
https://youtu.be/JiIyQaEyMX0

Content include:
- Running Remix using JS VM
- Configuring Metamask
- Getting ONE from the Faucet
- Deploying onto the Harmony One Testnet using Metamask

Length is 22 minutes. If we drop some content above this can reduce to the 15 minutes. Happy to adjust the video content and tutorial as required

**Comment by gupadhyaya** [comment]
thanks @sprect8 great video. but it is not addressing the topic of teaching solidity. the video is going over deploying solidity contracts, metamask harmony, etc, which is not the purpose here. the goal of this tutorial is to teach solidity programming by covering some of the solidity language constructs, examples, etc. If you see in https://learnxinyminutes.com/docs/solidity/, it goes over deployment briefly, then there are several solidity constructs explained in detail. We have to do the same. 

Your current video is still usable, but could you make another video separately focusing on describing the language constructs? 

I have doubled the reward, as this requires more work. Thank you for your help, greatly appreciate it.

**Comment by sprect8** [comment]
Hi @gupadhyaya thanks for the inputs this makes it much clearer.

I'll do a tutorial walking through each of the language constructs. That makes a lot of sense. I will also keep the current tutorial as - is and do a brief walkthrough of deploying the smart contracts focusing on the key points.

**Comment by sprect8** [comment]
Hi @gupadhyaya , @giv, please check out:
https://youtu.be/ii6A0wdzBAs

Github is: https://github.com/sprect8/learn-solidity-in-15-minutes

**Comment by gupadhyaya** [comment]
> https://youtu.be/ii6A0wdzBAs

waw. this is so nice. very thorough and superbly done. thank you.

**Comment by sprect8** [comment]
@gupadhyaya can I consider this task done?

I'll move on to the 20 minute dapp and submit within the next few days

Thanks!

**Comment by givp** [comment]
You nailed it

**Comment by sprect8** [comment]
Thanks @givp 

The latest video is at:
https://www.youtube.com/watch?v=ecCjyJShcGs

I put comments so viewers can follow along using remix, also linked the repo and pptx for downloads

**Comment by givp** [comment]
Forked: https://github.com/harmony-one/learn-solidity-in-15-minutes

**Comment by givp** [comment]
@sprect8 https://explorer.harmony.one/tx/0xdd830b13f4731e46fa852dc8b9cccd3653de05c312979396c7729da163dab6c9

**Comment by sprect8** [comment]
@givp received with thanks :)
