### ISSUE TITLE
[Open] Build a Dapp in 20 Minutes Tutorial

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/docs-home#23]
Replicate Dapp-university's Build a Dapp in 20 mins tutorial for harmony

Goals:
* Fork the repo: https://github.com/dappuniversity/20_minute_dapp
* Adjust to harmony deployment and walk through the steps in a README.md file and a video tutorial 
* Submit both modified repo and link to video tutorial

Reward
* 200 ONE w/o video
* 1000 ONE w/ video

**Comment by sprect8** [comment]
Hi, I am interested in doing this task

**Comment by sprect8** [comment]
@gupadhyaya wanted to confirm with you if this task involves creating a video similar to 
https://www.youtube.com/watch?v=KkZ6iYnSDRw

or a short video that will walkthrough getting the solution to run on harmony one testnet/ganache?

**Comment by gupadhyaya** [comment]
> @gupadhyaya wanted to confirm with you if this task involves creating a video similar to
> https://www.youtube.com/watch?v=KkZ6iYnSDRw
> 
> or a short video that will walkthrough getting the solution to run on harmony one testnet/ganache?

thanks for your interest @sprect8 
yes something similar to dapp universities length will be great, as this and solidity 101 are targeting web2 audience, so details are better. if you can still get it under 10 mins or max 15, ok.

**Comment by gupadhyaya** [comment]
@sprect8 how is it going with this tutorial? if you could finish it by this week, it will be great. thank you.

**Comment by sprect8** [comment]
Hi @gupadhyaya i have the writeup and will submit very soon :)

**Comment by sprect8** [comment]
Hi @giv, @gupadhyaya,

Please find the tutorial at: https://github.com/sprect8/20_minute_dapp
Page hosted at: https://sprect8.github.io/20_minute_dapp/
Youtube Video hosted at: https://youtu.be/aL3yLdZxOsM

Thanks! This was a lot of fun recording. Happy to change anything that might be missing.

**Comment by sprect8** [comment]
My one address is:
one1ft827spvu90ushltcnvq2cy3s6c2tedzkzlgpp

**Comment by gupadhyaya** [comment]
thanks @sprect8 
forked the repo [here](https://github.com/harmony-one/20_minute_dapp)
